# Generated by Django 4.2.5 on 2023-09-15 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("IventoryManager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory_items",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inventory_items",
            name="item_name",
            field=models.TextField(),
        ),
    ]
