# Generated by Django 4.2.5 on 2023-11-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "IventoryManager",
            "0002_inventory_items_user_alter_inventory_items_item_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory_items",
            name="dispatched_from",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="inventory_items",
            name="item_name",
            field=models.CharField(max_length=250),
        ),
    ]
